Add component Carousel
Skaant/rimarok-2 pull request #40
Opened 2022-06-14 12:27 UTC by Tim-jn

Fix #10

2022-06-15 06:18 UTC, Skaant requested changes
Au top ! Quelques changements pour améliorer l'affichage :)

Pense à pull mes modifications sur ta branche (il a fallu que je merge `dev` dessus)

2022-06-15 06:18 UTC, Skaant commented on src/components/Carousel.tsx
> +    <div id="carouselExampleIndicators" className="carousel slide" data-bs-ride="true">
Remplacer `id="carouselExampleIndicators"` par une prop `id`

2022-06-15 06:18 UTC, Skaant commented on src/components/Carousel.tsx
> +          data-bs-target="#carouselExampleIndicators"
Utiliser `id` aussi dans `data-bs-target="#carouselExampleIndicators"`

2022-06-15 06:18 UTC, Skaant commented on src/components/Carousel.tsx
> +        <button
Obtenir les boutons aussi via itérateur : leur nombre doit être le même que celui des `children`

2022-06-15 06:18 UTC, Skaant commented on src/components/Carousel.tsx
> +      <button
* Ajouter une prop `controlsColor` pour pouvoir customiser la couleur des flèches et textes,
* Supprimer `<span className="carousel-control-prev-icon" aria-hidden="true"></span>` (et next aussi),
* Remplacer les labels en dessous par "← Précédent" et "Suivant →"
* Aligner les contrôles en bas avec les boutons rectangulaires, mais avec une marge bottom pour pas que Prec/Suiv ne se chevauchent (exemple `d-flex align-items-end pb-5` sur le bouton)

2022-06-20 12:31 UTC, Tim-jn commented
Il faudra penser à modifier l'ID du carrousel

2022-06-20 12:57 UTC, Skaant commented
Yes effectivement !
Comme c'est une prop requise, on a peu de chances de le louper :)

2022-06-20 12:59 UTC, Skaant commented on src/styles/_utilities.scss
> +  ("background-color", true) // https://getbootstrap.com/docs/5.2/utilities/colors/
On dirait que nos configurations de prettier divergent et cela résulte en de nombreuses diffs inutiles :/

2022-06-20 13:25 UTC, Skaant approved these changes

2022-06-20 13:26 UTC, merged