Feature/#31 component badge list
Skaant/rimarok-2 pull request #41
Opened 2022-06-14 12:59 UTC by Tim-jn

Fix #31

2022-06-16 06:47 UTC, Skaant requested changes

2022-06-16 06:47 UTC, Skaant commented on src/components/BadgesList.tsx
> +          <span key={index} style={{ backgroundColor: badge.color }} className="badge rounded-pill">
Utilise les classes `bg-{COLORS}` plutôt que le style : 

Le nom des couleurs que j'ai défini sont propres au projet, décrites dans le SCSS et rendues dans les utilitaires Bootstrap (`bg-`, `text-` ...).
Par contre, ces noms n'ont pas de correspondance en CSS pur et ton implémentation n'affiche du coup pas les couleurs.

2022-06-16 06:47 UTC, Skaant commented on src/components/BadgesList.tsx
> +          <span key={index} style={{ backgroundColor: badge.color }} className="badge rounded-pill">
Tu peux aussi rajouter la classe `me-2` pour l'écart entre les badges.

2022-06-16 06:47 UTC, Skaant commented on src/components/BadgesList.tsx
> +    <span className="d-inline">
Un `span` est déjà inline, tu peux enlever la classe

2022-06-16 06:47 UTC, Skaant commented on src/components/BadgesList.tsx
> +        {badges.map((badge, index) => (
Prends l'habitude de destructurer les paramètres, sauf si tu as besoin de l'objet brut (pour une comparaison par exemple, ce qui n'est pas le cas ici) :

`badges.map(({ label, color }) => ...)`

2022-06-16 07:52 UTC, Tim-jn commented
Modifications effectuées :)

2022-06-20 12:55 UTC, Skaant approved these changes

2022-06-20 12:55 UTC, merged

2022-06-20 12:55 UTC, Skaant commented
@Tim-jn Impeccable :D
Pense à trouver plus imagé comme nom de commit (https://github.com/Skaant/rimarok-2/pull/41/commits/7741a83806bb0e795598756ff75d46c2b7e698fb ^^), quitte à en faire plusieurs, pour plus de clarté dans l'historique

2022-06-20 12:56 UTC, Tim-jn commented
> @Tim-jn Impeccable :D Pense à trouver plus imagé comme nom de commit ([7741a83](https://github.com/Skaant/rimarok-2/commit/7741a83806bb0e795598756ff75d46c2b7e698fb) ^^), quitte à en faire plusieurs, pour plus de clarté dans l'historique

ça marche :) !