Add component BackToTop
Skaant/rimarok-2 pull request #42
Opened 2022-06-14 13:51 UTC by Tim-jn

Fix #33

2022-06-14 13:52 UTC, Tim-jn commented
Il va falloir faire des modifications dans le fichier backToTop.js pour le backToTop button de la styleguide page

2022-06-16 07:16 UTC, Skaant requested changes

2022-06-16 07:16 UTC, Skaant commented on src/apps/backToTop.js
> +  topButton.style.display = window.scrollY > 200 ? "block" : "none";
Comme pour #41, privilégie l'emploie des classes (`d-block`, `d-none`) plutôt que tu style.

2022-06-16 07:16 UTC, Skaant commented on src/apps/backToTop.js
> +  topButton.style.display = window.scrollY > 200 ? "block" : "none";
Pour éviter de mettre à jour le DOM à chaque frame de scroll :

Avant l'instruction, mets un double test :
* < 200 && e.classList.contains('d-none') => rien
* < 200 && e.classList.contains('d-block') => change
* > 200 && e.classList.contains('d-block') => rien
* > 200 && e.classList.contains('d-none') => change

2022-06-16 07:16 UTC, Skaant commented on src/components/BackToTop.tsx
> +        isFixed ? "back-to-top-fixed btn rounded-circle" : "back-to-top-relative btn rounded-circle"
Fixed / relative : utiliser l'utilitaire `position-`

2022-06-16 07:16 UTC, Skaant commented on src/styles/components/_backToTop.scss
> +  position: fixed;
Pourquoi fixed et pas block ?

2022-06-21 15:51 UTC, Skaant commented on src/components/BackToTop.tsx
> +      } bottom-0 end-0 m-5 px-3 py-2 bg-${backgroundColor} text-${textColor}`}
Les utilities `bottom-0` et `end-0` doivent être activées ;)

2022-06-21 15:54 UTC, Skaant commented on src/components/BackToTop.tsx
> +function BackToTop({ isFixed = true, backgroundColor, textColor }: BackToTopProps) {
Par habitude, mettre des valeurs par défaut si la valeur doit être rendue.
Ex à éviter : `text-undefined`

Possibilité de rendre aussi avec : `textColor ? \` text-${textColor}\` : ''`.

Mais dans ce cas, je vais mettre le bg à LAGOON et le text à WHITE

2022-06-21 16:06 UTC, Skaant approved these changes

2022-06-21 16:06 UTC, Skaant commented on src/components/BackToTop.tsx
> +      className={`btn rounded-circle d-none border-0 ${
`rounded` à activer dans les utilities

2022-06-21 16:06 UTC, merged